#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Oct 02, 2019 02:47:14 PM IST  platform: Windows NT

import sys
from tkinter import messagebox
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
from PIL import Image,ImageTk
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = LoginPage (root)
    root.mainloop()

w = None
def create_LoginPage(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    rt = root
    w = tk.Toplevel (root)
    top = LoginPage (w)
    return (w, top)

def destroy_LoginPage():
    global w
    w.destroy()
    w = None

class LoginPage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Digital-7 Mono} -size 15 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        def login(event):
            userName = self.textUsername.get()
            password = self.textPassword.get()
            if userName=='' or password =='':
                self.lblCredential.configure(text='Please Provide all details')
            else:
#               messagebox.showwarning('Warning',)
                if userName =='admin' or userName=='ADMIN' or userName=='Admin':
                    if password == '12345' or password=='1234' or password== '123':
                        top.destroy()
                        import mainGUI
                        mainGUI.vp_start_gui()
                    else:
                        self.lblCredential.configure(text='Please Provide Valid Username and Password')
                else:
                    self.lblCredential.configure(text='Please Provide Valid Username and Password')

        top.geometry("563x395")
        top.title("Login Page")
        top.configure(background="#fbffff")
        top.configure(cursor="heart")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        windowWidth = 560
        windowHeight = 390
        positionRight = int(root.winfo_screenwidth()/2 - windowWidth/2)
        positionDown = int(root.winfo_screenheight()/2 - windowHeight/2)
        top.geometry("+{}+{}".format(positionRight, positionDown))


        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.675, rely=0.0, height=386, width=202)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"GUIImages/LoginBackGround.png")
        self._img0 = ImageTk.PhotoImage(Image.open(photo_location))
        self.Label1.configure(image=self._img0)
        self.Label1.configure(text='''Label''')


        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.444, rely=0.025, height=84, width=84)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"GUIImages/Login Icon3.png")
        self._img1 = ImageTk.PhotoImage(Image.open(photo_location))
        self.Label2.configure(image=self._img1)
        self.Label2.configure(text='''Label''')

        self.textUsername = tk.Entry(top)
        self.textUsername.place(relx=0.337, rely=0.304, height=44
                , relwidth=0.362)
        self.textUsername.configure(background="white")
        self.textUsername.configure(disabledforeground="#a3a3a3")
        self.textUsername.configure(font=font11)
        self.textUsername.configure(foreground="#3eaeef")
        self.textUsername.configure(highlightbackground="#3eaeef")
        self.textUsername.configure(highlightcolor="black")
        self.textUsername.configure(insertbackground="black")
        self.textUsername.configure(justify='center')
        self.textUsername.configure(readonlybackground="")
        self.textUsername.configure(relief="ridge")
        self.textUsername.configure(selectbackground="#c4c4c4")
        self.textUsername.configure(selectforeground="black")

        self.btnLogin = tk.Button(top)
        self.btnLogin.place(relx=0.284, rely=0.734, height=83, width=256)
        self.btnLogin.configure(activebackground="#ececec")
        self.btnLogin.configure(activeforeground="#000000")
        self.btnLogin.configure(background="#ffffff")
        self.btnLogin.configure(borderwidth="0")
        self.btnLogin.configure(disabledforeground="#a3a3a3")
        self.btnLogin.configure(foreground="#000000")
        self.btnLogin.configure(highlightbackground="#d9d9d9")
        self.btnLogin.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"GUIImages/loginbutton.png")
        self._img2 = ImageTk.PhotoImage(Image.open(photo_location))
        self.btnLogin.configure(image=self._img2)
        self.btnLogin.configure(pady="0")
        self.btnLogin.configure(text='''Button''')
        self.btnLogin.bind('<Button-1>',login)

        self.textPassword = tk.Entry(top)
        self.textPassword.place(relx=0.337, rely=0.481, height=44
                , relwidth=0.362)
        self.textPassword.configure(background="white")
        self.textPassword.configure(disabledforeground="#a3a3a3")
        self.textPassword.configure(font=font11)
        self.textPassword.configure(foreground="#3eaeef")
        self.textPassword.configure(highlightbackground="#3eaeef")
        self.textPassword.configure(highlightcolor="black")
        self.textPassword.configure(insertbackground="black")
        self.textPassword.configure(justify='center')
        self.textPassword.configure(readonlybackground="")
        self.textPassword.configure(relief="ridge")
        self.textPassword.configure(selectbackground="#c4c4c4")
        self.textPassword.configure(selectforeground="black")
        self.textPassword.configure(show='*')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.195, rely=0.456, height=54, width=54)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"GUIImages/PASSWOR.png")
        self._img3 = ImageTk.PhotoImage(Image.open(photo_location))
        self.Label3.configure(image=self._img3)
        self.Label3.configure(text='''Label''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.195, rely=0.278, height=54, width=54)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"GUIImages/usr.png")
        self._img4 = ImageTk.PhotoImage(Image.open(photo_location))
        self.Label4.configure(image=self._img4)
        self.Label4.configure(text='''Label''')

        self.lblCredential = tk.Label(top)
        self.lblCredential.place(relx=0.250, rely=0.633, height=29, width=300)
        self.lblCredential.configure(activebackground="#f9f9f9")
        self.lblCredential.configure(activeforeground="black")
        self.lblCredential.configure(background="#ffffff")
        self.lblCredential.configure(disabledforeground="#ff4314")
        self.lblCredential.configure(font=font12)
        self.lblCredential.configure(foreground="#ff6417")
        self.lblCredential.configure(highlightbackground="#d9d9d9")
        self.lblCredential.configure(highlightcolor="black")
        self.lblCredential.configure(text='''* Login Creditial''')

vp_start_gui()
